### ISSUE TITLE
[PE-D] Remove command can be more optimized for fast-typists

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-4/tp#186]
![image.png](https://raw.githubusercontent.com/LimJiaJing/ped/main/files/4bbaa074-09ad-480e-8af9-41bc2b6fb142.png)
Perhaps optional arguments could be provided to allow fast-typists to complete the task more quickly. Current version might have too many steps and cause inconvenience to the target user group. 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: LimJiaJing/ped#3

**Comment by alvynben** [comment]
While this command could be optimized for fast typists, most keyboard users would most likely prefer the approach used here as it is more forgiving and you don't need to remember the exact details of the item you want to delete from the start. Regardless, we may do this is future milestones.
