### ISSUE TITLE
[PE-D] No character limit on ingredient name

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-4/tp#197]
The user is able to key in a long long string into the list that does not make any sense.

Having an entry with so many characters could also make it hard for the user to remove this invalid input.

Perhaps the team would consider having a word limit?

Low severity as it doesn't affect functionality

![image.png](https://raw.githubusercontent.com/jhsee5/ped/main/files/cddfbf0d-0845-4791-82c8-399e84ac4150.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: jhsee5/ped#4

**Comment by alvynben** [comment]
No reason to restrict the user unnecessarily. And the remove command can for the item can be initiated by simply typing a part of the name.
