### ISSUE TITLE
[PE-D] Updating shotlist and include it in the list command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-4/tp#205]
Expected Output:  
After your team has fixed the shop list bugs, another suggestion from me is to have the shop list command inside the list command as something like "list -s". It would be better if the user can check the lists with the same command passing various flags only.
 
Actual Output:  
Currently, you are using the "shoplist" command.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Jiale-Sun/ped#4

**Comment by alvynben** [comment]
Rejected to keep shopping list separate from all other functions related to the Fridget. Thanks for the suggestion!
