### ISSUE TITLE
[PE-D] Finding the food items in different list

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-W12-4/tp#207]
Expected Output:  
After your team has fixed the shoplist bugs, another functionality that you might want to update is the "find" command. In this way, the user can choose to search for the food item in the fridge list or the shop list passing different flags, similar to the "list" command.

Actual Output:  
Currently, the "find" command is focusing on the fridge list.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: Jiale-Sun/ped#5

**Comment by alvynben** [comment]
The purpose of the shopping list is for users to add in or remove whatever items Fridget deems necessary to be added. What is more useful is the file stored in fridgetData. We've updated the UG to reflect this. Thanks!
